# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5020785bf1aca67f87b74919a2ebbee1c79b0a826b7ea82e55b00be0d52b06a9ca6c00b1a1fc4a86a66b78284741fb3b57d2b32e4a4238ee9db701101c406ac

test:
  secret_key_base: 332c28ee4d8ac6fc53ae20e8c38a5080bc77422057a0d9faacbf69611609293dbd66baa805989e0be0ccd3f0b0f13a2cd9de502d03bcca0617b5e20c5a593471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
