// I am an animu irl.
console.log("\nHello, World. Here I am.\n");

/* Euler Problem 1:
 * If we list all the natural numbers below 10 that are multiples 
 * of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
 *
 * Find the sum of all the multiples of 3 or 5 below 1000. 
 */
 
var euler1 = function (goal)
{
	// Simple error check.
	if(isNaN(goal))
		return "Error. NaN.";

	// Hold that sum!
	var sumMult = 0;

	// Add up mults of 3 that arent mults of 5.
	for(var i = 3; i < goal; i+=3)
	{
		if(i%5===0)
			continue;
		else
			sumMult += i;
	}

	// Add up mults of 5, even if mult of 3.
	for(var i = 5; i < goal; i += 5)
		sumMult += i;

	return sumMult;
}


/* Euler Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms.  By starting with 1 and 2, the first 
 * 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * By considering the terms in the Fibonacci sequence whose values 
 * do not exceed four million, find the sum of the even-valued 
 * terms. 
 */

var euler2 = function (goal)
{
	// Minor error check.
	if(isNaN(goal))
		return "Error. NaN.";

	// Sequence holders
	var xa = 1;
	var xb = 2;
	var evenSum = 2;

	while( xa < goal && xb < goal)
	{
		if(xa<xb)
		{
			xa += xb;
			if(!(xa%2))
				evenSum+=xa;	
		}
		else
		{
			xb += xa;
			if(!(xb%2))
				evenSum+=xb;
		}
	}

	return evenSum;
}


/* Euler Problem 3:
 * What is the largest prime factor of the number 600851475143 ?
 */

var euler3 = function (goal)
{
	// Minor error check.
	if(isNaN(goal))
		return "Error. NaN.";

	// Hold all prime factors! Why? I dunno!
	var factors = [];

	for(var i = 2; i*i < goal; i++)
		if(goal%i===0)
		{
			// Factor found!  Is it prime?
			var isPrime = true;
			for(var j = 2; j*j < i; j++)
			{
				if(i%j===0)
				{
					isPrime = false;
					break;
				}
			}
			// If the factor is prime, add it to the beginning 
			// of the array.
			if(isPrime)
				factors.unshift(i);
		}

	return factors[0];
}


console.log("Euler 1 Answer: " + euler1(1000));
console.log("Euler 2 Answer: " + euler2(4000000));
console.log("Euler 3 Answer: " + euler3(600851475143));